
<div class="display-sidebar-login">
<div class=content-column-login>
    <ul class="login-items-nav">
        <li>
            <strong class="list-style-nav">
            <?=("Mi cuenta")?> 
            </strong>
        </li>
        <li class="list-style-nav">
            <p>
            <?=("Mi cuenta corriente")?>
            </p>
        </li>
        <li class="list-style-nav">
            <p>
            <?=("Mi historial de pedidos")?>
            </p>
        </li>
        <li class="list-style-nav">
            <p>
            <?=("Mis comprobantes")?>
            </p>
        </li>
        <li class="list-style-nav">
            <p>
                <?=("Realizar un reclamo")?>
            </p>
        </li>

        <li class="list-style-nav">
            <p>
                <?=("Novedades")?>
            </p>
        </li>
        <li class="list-style-nav">
            <p>
                <?=("Catalogos")?>
            </p>
        </li>
        <li class="list-style-nav">
            <p>
                <?=("Nuestras Ofertas")?>
            </p>
        </li>
        <li class="list-style-nav">
            <p>
                <?=("Contacto")?>
            </p>
        </li>
    </ul>
</div>
</div>
