<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
            <li class="item product product-item">
                <div class="product-item-info"
                     id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                     data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = 'left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;';
                    }
                    ?>
                    <?php // Product Image ?>

                    <!-- Etiqueta de descuento -->
                    <div class="discount-content">
                        <p class="discount-text"><?=__("-30%")?></p>
                    </div>
                    
                    <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>

                    <!-- Attribute Stock -->
                    <div class="container-stock">
                        <span class="stock-image">
                            <img src="<?= $this->getViewFileUrl('images/plp/Vector.png') ?>" alt="">
                        </span>
                        <p class="stock-text"><?= __("In Stock") ?></p>
                    </div>

                    <!-- collapsibles -->
                    <div class="container-dropdowns-attributes container-dropdowns" data-mage-init='{"accordion":{
                                "openedState": "active",
                                "collapsible": true,
                                "active": false,
                                "animate":{ "duration" :300, "easing":"easeOutCubic"},
                                "multipleCollapsible": false}}'>
                        <div class="container-items dropdowns-deatils dropdowns" data-role="collapsible">
                            <div class="container-technical-details" data-role="trigger">
                                <div class="technical-details-title">
                                    <span class="technical-details-text"><?=__("Details")?></span>
                                    <span class="technical-details-img">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
                                        </svg>
                                    </span>
                                </div>
                            </div>
                            <div class="technical-details-content" data-role="content">
                                <div class="container-details details-content detail-gray">
                                    <p class="details-text"><?=__("IOMA")?></p>
                                    <p class="details-value"><?=__("$300.00")?></p>
                                </div>
                                <div class="container-details details-content">
                                    <p class="details-text"><?=__("PAMI 6")?></p>
                                    <p class="details-value"><?=__("50%")?></p>
                                </div>
                                <div class="container-details details-content detail-gray">
                                    <p class="details-text"><?=__("master box")?></p>
                                    <p class="details-value"><?=__("N/A")?></p>
                                </div>
                                <div class="container-details details-content">
                                    <p class="details-text"><?=__("expiration")?></p>
                                    <p class="details-value"><?=__("N/A")?></p>
                                </div>
                                <div class="container-details details-content detail-gray">
                                    <p class="details-text"><?=__("VAT")?></p>
                                    <p class="details-value"><?=__("No")?></p>
                                </div>
                                <div class="container-details details-content">
                                    <p class="details-text"><?=__("Pharmacy cost with tax")?></p>
                                    <p class="details-value"><?=__("$40.00")?></p>
                                </div>
                                <div class="container-details details-content detail-sku">
                                    <p class="details-text"><?=__("SKU")?></p>
                                    <p class="details-value"><?=__("IOSB00-776-3234MA")?></p>
                                </div>
                            </div>
                        </div>
                        <div class="container-items dropdowns-attachments dropdowns" data-role="collapsible">
                            <div class="attachments-details" data-role="trigger">
                                <div class="attachments-title">
                                    <span class="attachments-text"><?=__("Attachments")?></span>
                                    <span class="attachments-img">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
                                        </svg>
                                    </span>
                                </div>
                            </div>
                            <div class="attachments-content" data-role="content">
                                <div class="attachments-file">
                                    <div class="attachments-text-content">
                                        <img class="icon-download" src="<?= $this->getViewFileUrl('images/plp/download.png') ?>" alt=""></img>
                                        <p class="attachments-text"><?=__("Document’s name/format/(size)")?></p>
                                    </div>
                                    <div class="attachments-text-content">
                                        <img class="icon-downloadight" src="<?= $this->getViewFileUrl('images/plp/download.png') ?>" alt=""></img>
                                        <p class="attachments-text"><?=__("Document’s name/format/(size)")?></p>
                                    </div>
                                    <div class="attachments-text-content">
                                        <img class="icon-download" src="<?= $this->getViewFileUrl('images/plp/download.png') ?>" alt=""></img>
                                        <p class="attachments-text"><?=__("Document’s name/format/(size)")?></p>
                                    </div>
                                    <div class="attachments-text-content">
                                        <img class="icon-download" src="<?= $this->getViewFileUrl('images/plp/download.png') ?>" alt=""></img>
                                        <p class="attachments-text"><?=__("Document’s name/format/(size)")?></p>
                                    </div>
                                    <div class="attachments-text-content">
                                        <img class="icon-download" src="<?= $this->getViewFileUrl('images/plp/download.png') ?>" alt=""></img>
                                        <p class="attachments-text"><?=__("Document’s name/format/(size)")?></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="product details product-item-details">
                        
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <strong class="product name product-item-name">

                            <a class="product-item-link"
                               href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                            </a>

                            <!-- section tags -->
                            <div class="container-tags">
                                <div class="tags-content color-denim">
                                    <p class="text-tags"><?= __("hospitable")?></p>
                                </div>
                                <div class="tags-content color-azure">
                                    <p class="text-tags"><?= __("cold chain")?></p>
                                </div>
                                <div class="tags-content color-international-orange">
                                    <p class="text-tags"><?= __("no refund")?></p>
                                </div>
                                <div class="tags-content color-extremely-red">
                                    <p class="text-tags"><?= __("psychotropic")?></p>
                                </div>
                            </div>

                            <!-- section price details -->
                            <fidelset class="container-price-details">
                                <div class="price-details discount-price-details">
                                    <div class="price-details-content">
                                        <p class="price-title public-price-title"><?=__("Public price")?></p>
                                        <p class="public-price-content price-content"><?=__("$45.00")?></p>
                                    </div>
                                    <div class="price-details-content">
                                        <p class="price-title discount-price-title"><?=__("Discount")?></p>
                                        <p class="discount-price-content price-content"><?=__("25%")?></p>
                                    </div>
                                    <div class="price-details-content">
                                        <p class="price-title-total price-title"><?=__("Price")?></p>
                                        <p class="price-content-total price-content"><?=__("$34.00")?></p>
                                    </div>
                                </div>
                                <div class="price-details price-details-promotions promotions-carries-50-units">
                                    <div class="details-discount">
                                        <img class="icon-copyright" src="<?= $this->getViewFileUrl('images/plp/icon-discount-novelty.png') ?>" alt=""></img>
                                        <p class="text-carrying text"><?=__("carrying 50")?><b><?=__("you get 15% discount on PUB")?></b></p>
                                    </div>
                                    <div class="price-discount">
                                        <p class="text-price text"><?=__("$30.00")?></p>
                                    </div>
                                </div>
                                <div class="price-details price-details-promotions promotions-carries-50-units">
                                    <div class="details-discount">
                                        <img class="icon-copyright" src="<?= $this->getViewFileUrl('images/plp/icon-discount-novelty.png') ?>" alt=""></img>
                                        <p class="text-carrying text"><?=__("carrying 80")?><b><?=__("you get 18% discount on PUB")?></b></p>
                                    </div>
                                    <div class="price-discount">
                                        <p class="text-price text"><?=__("$28.00")?></p>
                                    </div>
                                </div>
                                <div class="price-details price-details-promotions promotions-carries-50-units">
                                    <div class="details-discount">
                                        <img class="icon-copyright" src="<?= $this->getViewFileUrl('images/plp/icon-discount-novelty.png') ?>" alt=""></img>
                                        <p class="text-carrying text"><?=__("carrying 100")?><b><?=__("you get 20% discount on PUB")?></b></p>
                                    </div>
                                    <div class="price-discount">
                                        <p class="text-price text"><?=__("$26.00")?></p>
                                    </div>
                                </div>
                            </fidelset>

                        </strong>
                        
                        <?php if ($showDescription): ?>

                            <div class="product description product-item-description">

                                <?= /* @noEscape */ $_helper->productAttribute(
                                    $_product,
                                    $_product->getShortDescription(),
                                    'short_description'
                                ) ?>
                                <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                                   title="<?= /* @noEscape */ $_productNameStripped ?>"
                                   class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?>
                                </a>
                            </div>
                        <?php endif; ?>
                        <!-- <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @noEscape */ $block->getProductPrice($_product) ?> -->

                        <?= $block->getProductDetailsHtml($_product) ?>
                        <div class="product-item-inner">

                            <!-- Input wicht arrow -->
                            <div class="arrow-input-container">
                                <div class="increase" id="increaseBtnP">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-dash-circle" viewBox="0 0 16 16">
                                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                        <path d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8z"/>
                                    </svg>
                                </div>
                                <input type="number">
                                <div class="decrease" id="decreaseBtnP">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                                    </svg>
                                </div>
                            </div>
                            
                            <div class="product actions product-item-actions">
                                <div class="actions-primary">
                                    <?php if ($_product->isSaleable()):?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                              data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                              action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                              method="post">
                                            <?php $options = $block->getData('viewModel')->getOptionsData($_product); ?>
                                            <?php foreach ($options as $optionItem): ?>
                                                <input type="hidden"
                                                       name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
                                                       value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
                                            <?php endforeach; ?>
                                            <input type="hidden"
                                                   name="product"
                                                   value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                            <input type="hidden"
                                                   name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                   value="<?=
                                                   /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                    ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                    class="action tocart primary"
                                                    disabled>
                                                <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        </form>
                                    <?php else:?>
                                        <?php if ($_product->isAvailable()):?>
                                            <div class="stock available">
                                                <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                        <?php else:?>
                                            <div class="stock unavailable">
                                                <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <?= ($pos && strpos($pos, $viewMode . '-primary')) ?
                                    /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                        $position,
                                        'product-item-info_' . $_product->getId() . ' div.actions-primary'
                                    ) : '' ?>
                            
                                <div data-role="add-to-links" class="actions-secondary">
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                           
                                <?= ($pos && strpos($pos, $viewMode . '-secondary')) ?
                                    /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                        $position,
                                        'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                                    ) : '' ?>
                            </div>
                        </div>
                    </div>

                </div>
                <?= ($pos && strpos($pos, $viewMode . '-actions')) ?
                /* @noEscape */ $secureRenderer->renderStyleAsTag(
                    $position,
                    'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                ) : '' ?>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>
    <script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {
                "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
            }
        }
    }
    </script>
<?php endif; ?>
