<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    $dataPersistor = $objectManager->get(Magento\Framework\App\Request\DataPersistor::class);
    $customer = $dataPersistor->get('customer');
    if (!$customer['email']) {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();

    $StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');

    ?>
    <div class="pages">
        <span  id="paging-label"><?=__('Productos por página:')?></span>
        <ul class="items pages-items" aria-labelledby="paging-label">
            <li class="item current">
                <strong class="page">
                    <span>9</span>
                </strong>
            </li>
            <li class="item">
                <a href="<?=$block->getUrl()?>&product_list_limit=27" class="page">
                    <span>27</span>
                </a>
            </li>
            <li class="item">
                <a href="<?=$block->getUrl()?>&product_list_limit=72" class="page">
                    <span>72</span>
                </a>
            </li>
        </ul>
    </div>

    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
            <li class="item product product-item">
                <div class="product-item-info"
                     id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                     data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = 'left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;';
                    }
                    ?>
                    <?php // Product Image ?>

                    <?php $discount = 0; if($customer['email'] && intval($_product->getData('price_incl_tax'))!=0):?>
                    <?php $discount = 100 - (intval($_product->getData('price'))*100)/intval($_product->getData('price_incl_tax'));
                            if($discount != 0):?>
                                <!-- Etiqueta de descuento -->
                                <div class="discount-content">
                                    <p class="discount-text"><?=intval($discount)?>%</p>
                                </div>
                            <?php endif;?>
                    <?php endif;?>

                    <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>

                    <!-- Attribute Stock -->
                    <div class="container-stock">
                    <?php if($StockState->getStockQty($_product->getId(), $_product->getStore()->getWebsiteId())): ?>
                        <span class="stock-image">
                            <img src="<?= $this->getViewFileUrl('images/plp/Vector.png') ?>" alt="">
                        </span>
                        <p class="stock-text <?=$_product->getData('qty')?>"><?= __("In Stock") ?></p>
                     <?php else:?>
                        <div class="stock unavailable">
                            <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                    <?php endif; ?>
                    </div>

                    <!-- collapsibles -->
                    <div class="container-dropdowns-attributes container-dropdowns" data-mage-init='{"accordion":{
                                "openedState": "active",
                                "collapsible": true,
                                "active": false,
                                "animate":{ "duration" :300, "easing":"easeOutCubic"},
                                "multipleCollapsible": false}}'>
                        <div class="container-items dropdowns-deatils dropdowns" data-role="collapsible">
                            <div class="container-technical-details" data-role="trigger">
                                <div class="technical-details-title">
                                    <span class="technical-details-text"><?=__("Details")?></span>
                                    <span class="technical-details-img">
                                        <img class="arrow-dropdowns" src="<?= $this->getViewFileUrl('images/plp/arrow-dropdowns.png') ?>" alt=""></img>
                                    </span>
                                </div>
                            </div>
                            <div class="technical-details-content" data-role="content">
                                <?php if($_product->getData('ioma')):?>
                                <div class="container-details details-content detail-gray">
                                    <p class="details-text"><?=__("IOMA")?></p>
                                    <p class="details-value">$<?=number_format($_product->getData('ioma'),2,'.',',')?></p>
                                </div>
                                <?php endif;?>
                                <?php if($_product->getData('ioma')):?>
                                <div class="container-details details-content">
                                    <p class="details-text"><?=__("PAMI")?></p>
                                    <p class="details-value"><?=$_product->getData('pami')?></p>
                                </div>
                                <?php endif;?>
                                <div class="container-details details-content detail-gray">
                                    <p class="details-text"><?=__("master box")?></p>
                                    <p class="details-value"><?=__("N/A")?></p>
                                </div>
                                <div class="container-details details-content">
                                    <p class="details-text"><?=__("expiration")?></p>
                                    <p class="details-value"><?=$_product->getData('valid_to')?></p>
                                </div>
                                <div class="container-details details-content detail-gray">
                                    <p class="details-text"><?=__("VAT")?></p>
                                    <p class="details-value"><?=$_product->getData('tax_code')?__("Si"):__("No")?></p>
                                </div>
                                <div class="container-details details-content">
                                    <p class="details-text"><?=__("Pharmacy cost with tax")?></p>
                                    <p class="details-value">$<?=number_format($_product->getData('price'),2,'.',',')?></p>
                                </div>
                                <div class="container-details details-content detail-sku">
                                    <p class="details-text"><?=__("SKU")?></p>
                                    <p class="details-value"><?=$_product->getSku()?></p>
                                </div>
                            </div>
                        </div>
                        <div class="container-items dropdowns-attachments dropdowns" data-role="collapsible">
                            <div class="attachments-details" data-role="trigger">
                                <div class="attachments-title">
                                    <span class="attachments-text"><?=__("Attachments")?></span>
                                    <span class="attachments-img">
                                        <img class="arrow-dropdowns" src="<?= $this->getViewFileUrl('images/plp/arrow-dropdowns.png') ?>" alt=""></img>
                                    </span>
                                </div>
                            </div>
                            <div class="attachments-content" data-role="content">
                                <div class="attachments-file">
                                    <div class="attachments-text-content">
                                        <img class="icon-download" src="<?= $this->getViewFileUrl('images/plp/download.png') ?>" alt=""></img>
                                        <p class="attachments-text"><?=__("Document’s name/format/(size)")?></p>
                                    </div>
                                    <div class="attachments-text-content">
                                        <img class="icon-downloadight" src="<?= $this->getViewFileUrl('images/plp/download.png') ?>" alt=""></img>
                                        <p class="attachments-text"><?=__("Document’s name/format/(size)")?></p>
                                    </div>
                                    <div class="attachments-text-content">
                                        <img class="icon-download" src="<?= $this->getViewFileUrl('images/plp/download.png') ?>" alt=""></img>
                                        <p class="attachments-text"><?=__("Document’s name/format/(size)")?></p>
                                    </div>
                                    <div class="attachments-text-content">
                                        <img class="icon-download" src="<?= $this->getViewFileUrl('images/plp/download.png') ?>" alt=""></img>
                                        <p class="attachments-text"><?=__("Document’s name/format/(size)")?></p>
                                    </div>
                                    <div class="attachments-text-content">
                                        <img class="icon-download" src="<?= $this->getViewFileUrl('images/plp/download.png') ?>" alt=""></img>
                                        <p class="attachments-text"><?=__("Document’s name/format/(size)")?></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="product details product-item-details">

                        <?php $_productNameStripped = $block->stripTags( $_product->getName(), null, true); ?>
                        <strong class="product name product-item-name">

                            <a class="product-item-link"
                               onclick="quickview.displayContent('weltpixel_quickview/catalog_product/view/id/<?=$_product->getId()?>')">
                                <?=/* @noEscape */ ucwords(strtolower($_helper->productAttribute($_product,$_product->getName(), 'name')))?>
                            </a>
                            <?php if ($customer['email']):?>
                            <!-- section tags -->
                            <div class="container-tags">
                                <div class="tags-content color-denim">
                                    <p class="text-tags"><?= __("hospitable")?></p>
                                </div>
                                <div class="tags-content color-azure">
                                    <p class="text-tags"><?= __("cold chain")?></p>
                                </div>
                                <div class="tags-content color-international-orange">
                                    <p class="text-tags"><?= __("no refund")?></p>
                                </div>
                                <div class="tags-content color-extremely-red">
                                    <p class="text-tags"><?= __("psychotropic")?></p>
                                </div>
                            </div>
                            <!-- section price details -->
                            <fidelset class="container-price-details">
                                <div class="price-details discount-price-details">
                                    <div class="price-details-content">
                                        <p class="price-title public-price-title"><?=__("Public price")?></p>
                                        <?php $price = $_product->getData('public_price')?$_product->getData('public_price'):$_product->getData('price');?>
                                        <p class="public-price-content price-content">$<?=number_format($price,2,'.',',')?></p>
                                    </div>
                                    <?php if($discount):?>
                                    <div class="price-details-content">
                                        <p class="price-title discount-price-title"><?=__("Discount")?></p>
                                        <p class="discount-price-content price-content"><?=intval($discount)?>%</p>
                                    </div>
                                    <?php endif;?>
                                    <div class="price-details-content">
                                        <p class="price-title-total price-title"><?=__("Price")?></p>
                                        <p class="price-content-total price-content">$<?php
                                            $price= $_product->getData('price_incl_tax')?floatval($_product->getData('price_incl_tax')):$_product->getData('price');
                                            echo number_format($price,2,'.',',')?></p>
                                    </div>
                                </div>
                                <div class="price-details price-details-promotions promotions-carries-50-units">
                                    <div class="details-discount">
                                        <img class="icon-copyright" src="<?= $this->getViewFileUrl('images/plp/icon-discount-novelty.png') ?>" alt=""></img>
                                        <p class="text-carrying text"><?=__("carrying 50")?><b><?=__("you get 15% discount on PUB")?></b></p>
                                    </div>
                                    <div class="price-discount">
                                        <p class="text-price text"><?=__("$30.00")?></p>
                                    </div>
                                </div>
                                <div class="price-details price-details-promotions promotions-carries-50-units">
                                    <div class="details-discount">
                                        <img class="icon-copyright" src="<?= $this->getViewFileUrl('images/plp/icon-discount-novelty.png') ?>" alt=""></img>
                                        <p class="text-carrying text"><?=__("carrying 80")?><b><?=__("you get 18% discount on PUB")?></b></p>
                                    </div>
                                    <div class="price-discount">
                                        <p class="text-price text"><?=__("$28.00")?></p>
                                    </div>
                                </div>
                                <div class="price-details price-details-promotions promotions-carries-50-units">
                                    <div class="details-discount">
                                        <img class="icon-copyright" src="<?= $this->getViewFileUrl('images/plp/icon-discount-novelty.png') ?>" alt=""></img>
                                        <p class="text-carrying text"><?=__("carrying 100")?><b><?=__("you get 20% discount on PUB")?></b></p>
                                    </div>
                                    <div class="price-discount">
                                        <p class="text-price text"><?=__("$26.00")?></p>
                                    </div>
                                </div>
                            </fidelset>
                            <?php endif;?>
                        </strong>

                        <?php if ($showDescription): ?>

                            <div class="product description product-item-description">

                                <?= /* @noEscape */ $_helper->productAttribute(
                                    $_product,
                                    $_product->getShortDescription(),
                                    'short_description'
                                ) ?>
                                <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                                   title="<?= /* @noEscape */ $_productNameStripped ?>"
                                   class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?>
                                </a>
                            </div>
                        <?php endif; ?>
                        <!-- <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @noEscape */ $block->getProductPrice($_product) ?> -->

                        <?= $block->getProductDetailsHtml($_product) ?>
                        <div class="product-item-inner">

                            <?php if ($customer['email']):?>
                            <!-- Input wicht arrow -->
                            <div class="arrow-input-container">
                                <div class="decrease" id="decreaseBtnP">
                                    <span class="icon-decrease"></span>
                                </div>
                                <input type="number">
                                <div class="increase" id="increaseBtnP">
                                    <span class="icon-increase"></span>
                                </div>
                            </div>
                            <?php endif;?>
                            <div class="product actions product-item-actions">
                                <div class="actions-primary">
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                              <?php if (!$customer['email']):?>
                                                  data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                                  action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                                  method="post"
                                                <?php endif;?>>
                                            <?php $options = $block->getData('viewModel')->getOptionsData($_product); ?>
                                            <?php foreach ($options as $optionItem): ?>
                                                <input type="hidden"
                                                       name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
                                                       value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
                                            <?php endforeach; ?>
                                            <input type="hidden"
                                                   name="product"
                                                   value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                            <input type="hidden"
                                                   name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                   value="<?=
                                                   /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                    ?>">
                                            <?= $block->getBlockHtml('formkey') ?>

                                            <?php if ($customer['email']):?>
                                            <button type="submit"
                                                    title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                    class="action tocart primary"
                                                    disabled>
                                                <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                            <?php else:?>
                                                <button onclick="jQuery('.header.links .authorization-link>a')[0].click();"
                                                        title="<?= $escaper->escapeHtmlAttr(__('Ingrese para comprar')) ?>"
                                                        class="action tocart primary"
                                                        disabled>
                                                    <span><?= $escaper->escapeHtml(__('Ingrese para comprar')) ?></span>
                                                </button>
                                            <?php endif;?>
                                        </form>
                                </div>
                                <?= ($pos && strpos($pos, $viewMode . '-primary')) ?
                                    /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                        $position,
                                        'product-item-info_' . $_product->getId() . ' div.actions-primary'
                                    ) : '' ?>

                                <div data-role="add-to-links" class="actions-secondary">
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>

                                <?= ($pos && strpos($pos, $viewMode . '-secondary')) ?
                                    /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                        $position,
                                        'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                                    ) : '' ?>
                            </div>
                        </div>
                    </div>

                </div>
                <?= ($pos && strpos($pos, $viewMode . '-actions')) ?
                /* @noEscape */ $secureRenderer->renderStyleAsTag(
                    $position,
                    'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                ) : '' ?>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>
    <script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {
                "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
            }
        }
    }
    </script>
<?php endif; ?>
