<div class="bottom-bar-footer">
    <div class="copyright-content">
        <img class="icon-copyright" src="<?= $this->getViewFileUrl('images/footer/copyright.png') ?>" alt=""></img>
        <p class="text-copyright text"><?=__('2022 Ballon Group SRL')?></p>
    </div>
    <div class="clsFooterLogos">
        <div class="clsLogo">
            <a href="#">
                <img src="https://stg.sumed.bgroup.com.ar/media/wysiwyg/facebook.png" alt="" width="32" height="auto"/>
            </a>
        </div>
        <div class="clsLogo">
            <a href="#">
                <img src="https://stg.sumed.bgroup.com.ar/media/wysiwyg/instagram.png" alt="" width="32" height="auto" />
            </a>
        </div>
        <div class="clsLogo">
            <a href="#">
                <img src="https://stg.sumed.bgroup.com.ar/media/wysiwyg/youtube.png" alt="" width="32" height="auto" />
        </a>
        </div>
    </div>
    <div class="logo-sumed">

        <img src="<?= $this->getViewFileUrl('images/footer/SUMED-logo-color-2.png') ?>" alt="">
    </div>
</div>