<div class="bottom-bar-footer">
    <div class="copyright-content">
        <img class="icon-copyright" src="<?= $this->getViewFileUrl('images/footer/copyright.png') ?>" alt=""></img>
        <p class="text-copyright text"><?=__('2022 Ballon Group SRL')?></p>
    </div>
    <div class="clsFooterLogosCommerces">
        <div class="clsLogo">
            <a href="#">
                <img src="https://stg.sumed.bgroup.com.ar/media/wysiwyg/facebook.png" alt="" width="32" height="auto"/>
            </a>
    
            <a href="#">
                <img src="https://stg.sumed.bgroup.com.ar/media/wysiwyg/instagram.png" alt="" width="32" height="auto" />
            </a>
        <a href="#"><img src="https://stg.sumed.bgroup.com.ar/media/wysiwyg/youtube.png" alt="" width="32" height="auto" /></a>
        </div>
    </div>
    
</div>