<section class="sections-footer-container">
    <div class="section-newsletter-footer">
    <img src="https://stg.sumed.bgroup.com.ar/media/wysiwyg/pearl_theme/SUMED-logo-color-2.png" alt="" />
    </div>
    <div class="link-sections-footer">   
        <div class="sections section-how-buy">
            <h4 class="title-category title buy-now-category"><?=__("Nosotros")?></h4>
            <ul class="links">
                <li class="link-li"><a href="#" class="link"><?=__("Sobre nosotros")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Prensa")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Para proveedores")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Regulaciones")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Privacidad")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Cookies")?></a></li>
            </ul>
        </div>
        <div class="sections section-how-buy">
            <h4 class="title-category title buy-now-category"><?=__("Cómo comprar")?></h4>
            <ul class="links">
                <li class="link-li"><a href="#" class="link"><?=__("Métodos de pago")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Retiro a depósito")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Compra con envío")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Compras telefónicas")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Devoluciones")?></a></li>
            </ul>
        </div>
        <div class="sections section-Services">
            <h4 class="title-category title servicios-category"><?=__("Servicios")?></h4>
            <ul class="links">
                <li class="link-li"><a href="#" class="link"><?=__("Logística")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Atención al cliente")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Devoluciones")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Otros servicios")?></a></li>
            </ul>
        </div>
        <div class="sections section-helps">
            <h4 class="title-category title Ayuda-category"><?=__("Ayuda")?></h4>
            <ul class="links">
                <li class="link-li"><a href="#" class="link"><?=__("Contacto")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Ayuda online")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Nuestro compromiso")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Dar feedback")?></a></li>
            </ul>
        </div>
    </div>
</section>