<section class="sections-footer-container">
    <div class="section-newsletter-footer">
    <img src="https://stg.sumed.bgroup.com.ar/media/wysiwyg/pearl_theme/SUMED-logo-color-2.png" alt="" />
    </div>
    <div class="link-sections-footer">   
        <div class="sections section-how-buy">
            <h4 class="title-category title buy-now-category"><?=__("Sobre Nosotros")?></h4>
            <ul class="links">
                <li class="link-li"><a href="#" class="link"><?=__("Sobre nosotros")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Prensa")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Para proveedores")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Regulaciones")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Privacidad")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Cookies")?></a></li>
            </ul>
        </div>
        <div class="sections section-how-buy">
            <h4 class="title-category title buy-now-category"><?=__("How to buy")?></h4>
            <ul class="links">
                <li class="link-li"><a href="#" class="link"><?=__("Payment methods")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("withdrawal to deposit")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Buy with shipping")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Telephone purchases")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("returns")?></a></li>
            </ul>
        </div>
        <div class="sections section-Services">
            <h4 class="title-category title servicios-category"><?=__("Services")?></h4>
            <ul class="links">
                <li class="link-li"><a href="#" class="link"><?=__("Logistics")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Customer Support")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("returns")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Other services")?></a></li>
            </ul>
        </div>
        <div class="sections section-helps">
            <h4 class="title-category title Ayuda-category"><?=__("Help")?></h4>
            <ul class="links">
                <li class="link-li"><a href="#" class="link"><?=__("Contact")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Online Help")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Our commitment")?></a></li>
                <li class="link-li"><a href="#" class="link"><?=__("Give feedback")?></a></li>
            </ul>
        </div>
    </div>
</section>