<!-- collapsibles -->
<div class="container-dropdowns-attributes container-dropdowns" data-mage-init='{"accordion":{
    "openedState": "active",
    "collapsible": true,
    "active": false,
    "animate":{ "duration" :300, "easing":"easeOutCubic"},
    "multipleCollapsible": false}}'>
    <div class="container-items dropdowns-deatils dropdowns" data-role="collapsible">
        <div class="container-technical-details" data-role="trigger">
            <div class="technical-details-title">
                <span class="technical-details-text"><?=__("Details")?></span>
                <span class="technical-details-img">
                    <img class="arrow-dropdowns" src="<?= $this->getViewFileUrl('images/plp/arrow-dropdowns.png') ?>" alt=""></img>
                </span>
            </div>
        </div>
        <div class="technical-details-content" data-role="content">
            <div class="container-details details-content detail-gray">
                <p class="details-text"><?=__("IOMA")?></p>
                <p class="details-value"><?=__("$300.00")?></p>
            </div>
            <div class="container-details details-content">
                <p class="details-text"><?=__("PAMI 6")?></p>
                <p class="details-value"><?=__("50%")?></p>
            </div>
            <div class="container-details details-content detail-gray">
                <p class="details-text"><?=__("master box")?></p>
                <p class="details-value"><?=__("N/A")?></p>
            </div>
            <div class="container-details details-content">
                <p class="details-text"><?=__("expiration")?></p>
                <p class="details-value"><?=__("N/A")?></p>
            </div>
            <div class="container-details details-content detail-gray">
                <p class="details-text"><?=__("VAT")?></p>
                <p class="details-value"><?=__("No")?></p>
            </div>
            <div class="container-details details-content">
                <p class="details-text"><?=__("Pharmacy cost with tax")?></p>
                <p class="details-value"><?=__("$40.00")?></p>
            </div>
            <div class="container-details details-content detail-sku">
                <p class="details-text"><?=__("SKU")?></p>
                <p class="details-value"><?=__("IOSB00-776-3234MA")?></p>
            </div>
        </div>
    </div>
    <div class="container-items dropdowns-attachments dropdowns" data-role="collapsible">
        <div class="attachments-details" data-role="trigger">
            <div class="attachments-title">
                <span class="attachments-text"><?=__("Attachments")?></span>
                <span class="attachments-img">
                <img class="arrow-dropdowns" src="<?= $this->getViewFileUrl('images/plp/arrow-dropdowns.png') ?>" alt=""></img>
                </span>
            </div>
        </div>
        <div class="attachments-content" data-role="content">
            <div class="attachments-file">
                <div class="attachments-text-content">
                    <img class="icon-download" src="<?= $this->getViewFileUrl('images/plp/download.png') ?>" alt=""></img>
                    <p class="attachments-text"><?=__("Document’s name/format/(size)")?></p>
                </div>
                <div class="attachments-text-content">
                    <img class="icon-downloadight" src="<?= $this->getViewFileUrl('images/plp/download.png') ?>" alt=""></img>
                    <p class="attachments-text"><?=__("Document’s name/format/(size)")?></p>
                </div>
                <div class="attachments-text-content">
                    <img class="icon-download" src="<?= $this->getViewFileUrl('images/plp/download.png') ?>" alt=""></img>
                    <p class="attachments-text"><?=__("Document’s name/format/(size)")?></p>
                </div>
                <div class="attachments-text-content">
                    <img class="icon-download" src="<?= $this->getViewFileUrl('images/plp/download.png') ?>" alt=""></img>
                    <p class="attachments-text"><?=__("Document’s name/format/(size)")?></p>
                </div>
                <div class="attachments-text-content">
                    <img class="icon-download" src="<?= $this->getViewFileUrl('images/plp/download.png') ?>" alt=""></img>
                    <p class="attachments-text"><?=__("Document’s name/format/(size)")?></p>
                </div>
            </div>
        </div>
    </div>
</div>