<!-- section price details -->

<fidelset class="container-price-details">

    <div class="price-details discount-price-details">
        <div class="price-details-content">
            <p class="price-title public-price-title"><?=__("Public price")?></p>
            <p class="public-price-content price-content"><?=__("$45.00")?></p>
        </div>
        <div class="price-details-content">
            <p class="price-title discount-price-title"><?=__("Discount")?></p>
            <p class="discount-price-content price-content"><?=__("25%")?></p>
        </div>
        <div class="price-details-content">
            <p class="price-title-total price-title"><?=__("Price")?></p>
            <p class="price-content-total price-content"><?=__("$34.00")?></p>
        </div>
    </div>

    <div class="price-details price-details-promotions promotions-carries-50-units">
        <div class="details-discount">
            <img class="icon-copyright" src="<?= $this->getViewFileUrl('images/plp/icon-discount-novelty.png') ?>" alt=""></img>
            <p class="text-carrying text"><?=__("carrying 50")?><b><?=__("you get 15% discount on PUB")?></b></p>
        </div>
        <div class="price-discount">
            <p class="text-price text"><?=__("$30.00")?></p>
        </div>
    </div>

    <div class="price-details price-details-promotions promotions-carries-50-units">
        <div class="details-discount">
            <img class="icon-copyright" src="<?= $this->getViewFileUrl('images/plp/icon-discount-novelty.png') ?>" alt=""></img>
            <p class="text-carrying text"><?=__("carrying 80")?><b><?=__("you get 18% discount on PUB")?></b></p>
        </div>
        <div class="price-discount">
            <p class="text-price text"><?=__("$28.00")?></p>
        </div>
    </div>

    <div class="price-details price-details-promotions promotions-carries-50-units">
        <div class="details-discount">
            <img class="icon-copyright" src="<?= $this->getViewFileUrl('images/plp/icon-discount-novelty.png') ?>" alt=""></img>
            <p class="text-carrying text"><?=__("carrying 100")?><b><?=__("you get 20% discount on PUB")?></b></p>
        </div>
        <div class="price-discount">
            <p class="text-price text"><?=__("$26.00")?></p>
        </div>
    </div>

</fidelset>