<!-- collapsibles -->
<div class="container-dropdowns-attributes container-dropdowns" data-mage-init='{"accordion":{
            "openedState": "active",
            "collapsible": true,
            "active": false,
            "animate":{ "duration" :300, "easing":"easeOutCubic"},
            "multipleCollapsible": false}}'>
    <div class="container-items dropdowns-deatils dropdowns" data-role="collapsible">
        <div class="container-technical-details" data-role="trigger">
            <div class="technical-details-title">
                <span class="technical-details-text"><?=__("Technical details")?></span>
                <span class="technical-details-img">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
                    </svg>
                </span>
            </div>
        </div>
        <div class="technical-details-content" data-role="content">
            <p class="text-attribute">5</p>
            <p class="text-attribute">6</p>
        </div>
    </div>
    <div class="container-items dropdowns-attachments dropdowns" data-role="collapsible">
        <div class="attachments-details" data-role="trigger">
            <div class="attachments-title">
                <span class="attachments-text"><?=__("Attachments")?></span>
                <span class="attachments-img">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
                    </svg>
                </span>
            </div>
        </div>
        <div class="attachments-content" data-role="content">
            <p class="text-attribute">7</p>
            <p class="text-attribute">8</p>
        </div>
    </div>
</div>