<?php
    /**
     * @var \AgSoftware\Login\Block\Columna $block;
     **/
    if(!$block->isLoggedIn()){
        return;
    }
?>
<div class="display-sidebar-login">
<div class=content-column-login>
    <ul class="login-items-nav">
    <li class="list-colunm-nav">
            <div class="container-column">
            <img src="<?= $this->getViewFileUrl('images/footer/SUMED-logo-color-2.png') ?>" alt="">
            
            </div>
           
        </li>
        <li class="list-colunm-nav">
            <div class="container-text-data space-text">
            <span class="text">
               <?=__("Hola,");?>
            </span>
            <span class="text-description">
               <?=__("FARMACIA DEL SUR");?>
            </span>
            </div>
           
        </li>
        <li class="list-colunm-nav">
            <div class="container-column">
            <img src="<?= $this->getViewFileUrl('images/column/mi-cuenta.png') ?>" alt="">
            <span class="list-style-nav">
               <?=__("My Account");?>
            </span>
            </div>
           
        </li>
        <li class="list-colunm-nav">
            <div  class="container-column">
                <img src="<?= $this->getViewFileUrl('images/column/cuenta_corriente.png') ?>" alt="">

                <span class="list-style-nav"><?=__("Mi cuenta corriente")?></span>
            </div>
        </li>

        <li class="list-colunm-nav">

            <div  class="container-column">

                <img src="<?= $this->getViewFileUrl('images/column/historial_pedidos.png') ?>" alt="">
                <span class="list-style-nav"><?=__("Mi historial de pedidos")?></span>

            </div>

        </li>
        <li class="list-colunm-nav">
        <div  class="container-column">
        <img src="<?= $this->getViewFileUrl('images/column/comprobantes.png') ?>" alt="">

        <span class="list-style-nav"><?=__("Mis comprobantes")?></span>


        </div>
        </li>
        <li class="list-colunm-nav">
        <div  class="container-column">
        <img src="<?= $this->getViewFileUrl('images/column/reclamo.png') ?>" alt="">

        <span class="list-style-nav"><?=__("Realizar un reclamo")?></span>


        </div>
        </li>

        <li class="list-colunm-nav">
        <div  class="container-column">
        <img src="<?= $this->getViewFileUrl('images/column/novedades.png') ?>" alt="">

        <span class="list-style-nav"><?=__("Novedades")?></span>


        </div>
        </li>
        <li class="list-colunm-nav">
        <div  class="container-column">
        <img src="<?= $this->getViewFileUrl('images/column/catalogos.png') ?>" alt="">

        <span class="list-style-nav"><?=__("Catalogos")?></span>


        </div>
        </li>
        <li class="list-colunm-nav">
        <div  class="container-column">
        <img src="<?= $this->getViewFileUrl('images/column/ofertas.png') ?>" alt="">

        <span class="list-style-nav"><?=__("Nuestras Ofertas")?></span>


        </div>
        </li>
        
        <li class="list-colunm-nav">
        <div  class="container-column">
        <img src="<?= $this->getViewFileUrl('images/column/contacto.png') ?>" alt="">

        <span class="list-style-nav"><?=__("Contacto")?></span>

        </div>
        </li>

        <li class="list-colunm-nav space-exit">
        <div  class="container-column">
        <img src="<?= $this->getViewFileUrl('images/column/salir.png') ?>" alt="">

        <span class="list-style-exit"><?=__("salir")?></span>

        </div>
        </li>
    </ul>
</div>
</div>
