<?php
    /**
     * @var \AgSoftware\Login\Block\Columna $block;
     **/
    if(!$block->isLoggedIn()){
        return;
    }
?>
<div class="display-sidebar-login">
<div class=content-column-login>
    <ul class="login-items-nav">
    <li class="list-colunm-nav">
            <div class="container-column">
            <a href="home-commerce-logged/"><img src="<?= $this->getViewFileUrl('images/footer/SUMED-logo-color-2.png') ?>" alt=""></a>
            
            </div>
           
        </li>
        <li class="list-colunm-nav">
            <div class="container-text-data space-text">
            <span class="text">
               <?=__("Hola,");?>
            </span>
            <span class="text-description">
               <?=__("FARMACIA DEL SUR");?>
            </span>
            </div>
           
        </li>
        <li class="list-colunm-nav">
            <div class="container-column">
            <img src="<?= $this->getViewFileUrl('images/column/person_outline.svg') ?>" alt="">
            <span class="list-style-nav">
               <?=__("My Account");?>
            </span>
            </div>
           
        </li>
        <li class="list-colunm-nav">
            <div  class="container-column">
                <img src="<?= $this->getViewFileUrl('images/column/corriente.svg') ?>" alt="">

                <span class="list-style-nav"><?=__("Mi cuenta corriente")?></span>
            </div>
        </li>

        <li class="list-colunm-nav">

            <div  class="container-column">

                <img src="<?= $this->getViewFileUrl('images/column/historial.svg') ?>" alt="">
                <span class="list-style-nav"><?=__("Mi historial de pedidos")?></span>

            </div>

        </li>
        <li class="list-colunm-nav">
        <div  class="container-column">
        <img src="<?= $this->getViewFileUrl('images/column/comprobantes.svg') ?>" alt="">

        <span class="list-style-nav"><?=__("Mis comprobantes")?></span>


        </div>
        </li>
        <li class="list-colunm-nav">
        <div  class="container-column">
        <img src="<?= $this->getViewFileUrl('images/column/reclamos.svg') ?>" alt="">

        <span class="list-style-nav"><?=__("Realizar un reclamo")?></span>


        </div>
        </li>

        <li class="list-colunm-nav">
        <div  class="container-column">
        <img src="<?= $this->getViewFileUrl('images/column/novedades.svg') ?>" alt="">

        <span class="list-style-nav"><?=__("Novedades")?></span>


        </div>
        </li>
        <li class="list-colunm-nav">
        <div  class="container-column">
        <img src="<?= $this->getViewFileUrl('images/column/catalogo.svg') ?>" alt="">

        <span class="list-style-nav"><?=__("Catalogos")?></span>


        </div>
        </li>
        <li class="list-colunm-nav">
        <div  class="container-column">
        <img src="<?= $this->getViewFileUrl('images/column/ofertas.svg') ?>" alt="">

        <span class="list-style-nav"><?=__("Nuestras Ofertas")?></span>


        </div>
        </li>
        
        <li class="list-colunm-nav">
        <div  class="container-column">
        <img src="<?= $this->getViewFileUrl('images/column/contacto.svg') ?>" alt="">

        <span class="list-style-nav"><?=__("Contacto")?></span>

        </div>
        </li>

        <li class="list-colunm-nav space-exit">
        <div  class="container-column">
        <img src="<?= $this->getViewFileUrl('images/column/salir.png') ?>" alt="">

        <span class="list-style-nav" style="color:red"><?=__("Exit")?></span>

        </div>
        </li>
    </ul>
</div>
</div>
<script>
    require(['jquery'], function($) {
        jQuery( document ).ready(function() {
            if (jQuery( "#login-column" ).length == 0) {
                return;
            }
            jQuery( "#login-column" )
                .focusout(function() {
                    console.log('focusout');
                    jQuery( "#maincontent" ).css( "margin-left",  "0");
                })
                .blur(function() {
                    console.log('blur');
                    jQuery( "#maincontent" ).css( "margin-left",  jQuery( "#login-column" ).width() + "px");
                });
        });
    });
</script>