<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$dataPersistor = $objectManager->get(Magento\Framework\App\Request\DataPersistor::class);
$customer = $dataPersistor->get('customer');
if (isset($customer['email']) && $customer['email']):?>
<script type="text/javascript">
    require(['jquery'],function($) {
        $('body').addClass('logged');
        $('#cerrado').hide();
        $('.content-column-login').hover(
            function () {
                $('#abierto').show();
                $('#cerrado').hide();
                $('.page-wrapper').attr('style', 'margin-left:252px;margin-right:30px');
            },
            function () {
                $('#abierto').hide();
                $('#cerrado').show();
                $('.page-wrapper').attr('style', 'margin-left:72px');
            }
        );
    });
</script>
<div id="login-column" class="display-sidebar-login" data-bind="scope:'login-column'">
<!-- ko if: getFullName() -->
<div class=content-column-login>
    <ul class="login-items-nav">
    <li class="list-colunm-nav" onclick="location.href='<?=$block->getUrl()?>'">
            <div class="container-column">
            <a href="/commerce/home-commerce-logged/">
                <img id="abierto" src="<?= $this->getViewFileUrl('images/footer/SUMED-logo-color-2.png')  ?>" style="diplay:none" alt=""></a>
                <img id="cerrado" src="/pub/media/wysiwyg/Vector_2.png"   style="diplay:block" alt=""></a>
            </div>

        </li>
        <li class="list-colunm-nav">
            <div class="container-text-data space-text">
            <span class="text">
               <?=__("Hola,");?>
            </span>
                <span class="text-description"><?=$customer['firstname']." ".$customer['lastname']?></span>
            </span>
            </div>

        </li>
        <li class="list-colunm-nav">
            <div class="container-column">
            <img src="<?= $this->getViewFileUrl('images/column/person_outline.svg') ?>" alt="">
            <span class="list-style-nav">
               <?=__("My Account");?>
            </span>
            </div>

        </li>
        <li class="list-colunm-nav" onclick="location.href='<?=$block->getUrl('customer/account/')?>'">
            <div  class="container-column">
                <img src="<?= $this->getViewFileUrl('images/column/corriente.svg') ?>" alt="">

                <span class="list-style-nav"><?=__("Mi cuenta corriente")?></span>
            </div>
        </li>

        <li class="list-colunm-nav" onclick="location.href='<?=$block->getUrl('customer/account/')?>'">
            <div  class="container-column">
                <img src="<?= $this->getViewFileUrl('images/column/historial.svg') ?>" alt="">
                <span class="list-style-nav"><?=__("Mi historial de pedidos")?></span>
            </div>
        </li>
        <li class="list-colunm-nav">
        <div  class="container-column">
        <img src="<?= $this->getViewFileUrl('images/column/comprobantes.svg') ?>" alt="">

        <span class="list-style-nav"><?=__("Mis comprobantes")?></span>


        </div>
        </li>
        <li class="list-colunm-nav" onclick="location.href='<?=$block->getUrl('customer/account/')?>'">
        <div  class="container-column">
        <img src="<?= $this->getViewFileUrl('images/column/reclamos.svg') ?>" alt="">

        <span class="list-style-nav"><?=__("Realizar un reclamo")?></span>


        </div>
        </li>

        <li class="list-colunm-nav" onclick="location.href='<?=$block->getUrl('customer/account/')?>'">
        <div  class="container-column">
        <img src="<?= $this->getViewFileUrl('images/column/novedades.svg') ?>" alt="">

        <span class="list-style-nav"><?=__("Novedades")?></span>


        </div>
        </li>
        <li class="list-colunm-nav" onclick="location.href='<?=$block->getUrl('customer/account/')?>'">
        <div  class="container-column">
        <img src="<?= $this->getViewFileUrl('images/column/catalogo.svg') ?>" alt="">

        <span class="list-style-nav"><?=__("Catalogos")?></span>


        </div>
        </li>
        <li class="list-colunm-nav" onclick="location.href='<?=$block->getUrl('customer/account/')?>'">
        <div  class="container-column">
        <img src="<?= $this->getViewFileUrl('images/column/ofertas.svg') ?>" alt="">

        <span class="list-style-nav"><?=__("Nuestras Ofertas")?></span>


        </div>
        </li>

        <li class="list-colunm-nav" onclick="location.href='<?=$block->getUrl('customer/account/')?>'">
        <div  class="container-column">
        <img src="<?= $this->getViewFileUrl('images/column/contacto.svg') ?>" alt="">

        <span class="list-style-nav"><?=__("Contacto")?></span>

        </div>
        </li>

        <li class="list-colunm-nav space-exit" onclick="location.href='<?=$block->getUrl('customer/account/logout')?>'" style="cursor:pointer;">
        <div  class="container-column">
        <img src="<?= $this->getViewFileUrl('images/column/salir.png') ?>" alt="">

        <span class="list-style-nav" style="color:red"><?=__("Exit")?></span>

        </div>
        </li>
    </ul>
</div>
<!-- /ko -->
</div>
<?php endif;?>
